# file: group_vars
###############################################################################
#
#                  ////IMPORTANT////
#
#      Prefixed to all resources for cleanup & identifcation.
###############################################################################

# Ensure that the name does not include special characters such as underscores, etc.
workshop_prefix:                  "container" # Workshop name - NO underscores!
workshop_phase:                   "prod" # Can be "dev", "test", or "prod"
workshop_appCode:                 "????" # Waiting for code creation
execution:                        "local" # when not running from Tower, define this variable
jboss:                            false # when true, configure JBoss/Maven
graphical:                        false # when true, install a graphical desktop on the tower nodes
beta:                             false # when true, use beta respoitories

###############################################################################
# ANSIBLE ROLE KEY         |      VALUE
###############################################################################
# aws                      |      deployment working dir 
deploy_working_dir:               "{{ lookup('env','PWD') }}/.redhatgov"
# aws                      |      AWS Route 53
domain_name:                      ""
zone_id:                          ""
# aws                      |      AWS Node Counts
student_count:                    "2"            # Number of students attending
student_nodes_count:              "2"            # Number of nodes per student
win_count:                        "0"            # Windows node(s)
#------------------------------------------------------------------------------
# AWS Region, configures ec2.ini too.  Supported are: us-east-[1,2],us-west-1,eu-central-1
#region:                           "us-east-1"
region:                           "us-east-2"
#region:                           "us-west-1"
#region:                           "eu-central-1"
#------------------------------------------------------------------------------
# AMI details
# these values are substrings of AMI names
#rhel_ver:                         "RHEL-7"
rhel_ver:                         "RHEL-8"
win_ver:                          "Windows_Server-2016"
ebs_root_block_size:              50
auto_ami:                         true           # automatically identify AMI in selected region
#------------------------------------------------------------------------------
# instance_types
win_instance_type:                "t3a.large"
bastion_instance_type:            "t3a.large"
rhel_instance_type:               "t3a.small"
#------------------------------------------------------------------------------
# subscription_manager     |      Red Hat Subscription via Cloud Access
cloud_access:                     true
# subscription_manager     |      Red Hat Subscription via username & password
username:                         ""
password:                         ""
pool_id:                          ""
# subscription_manager     |      Red Hat Subscription via activation keys
rhsm_activationkey:               ""
rhsm_org_id:                      ""
#------------------------------------------------------------------------------
# LetsEncrypt              |      email
letsencrypt_email:                "someone@redhat.com"
#------------------------------------------------------------------------------
# console                  |      password
workshop_password:                "" # Note that Windows 2016 requires 3 character classes and 10 characters
#------------------------------------------------------------------------------
# ports to open            |      Add any ports that you may need to this dict
ports:
  tcp:
    22:
    - "ssh"
    80:
    - "http"
    443:
    - "https"
    3389:
    - "rdp"
    5000:
    - "registry"
    5986:
    - "winrm https"
    8080:
    - "jboss"
    8443:
    - "vscode"
    8888:
    - "wetty"
    9090:
    - "cockpit"
  udp: 
#    53:
#    - "dns"
###############################################################################
# ANSIBLE config           |      VALUE
###############################################################################
# Dynamic Inventory 
inventory_working_dir:            "{{ lookup('env','PWD') }}/inventory"
# Ansible SSH Key Location |      SSH Key Vars
winrm_path:                       "{{ deploy_working_dir }}/{{ workshop_prefix }}-winrm"
ssh_key_path:                     "{{ deploy_working_dir }}/{{ workshop_prefix }}-key"
vpc_id_path:                      "{{ deploy_working_dir }}/{{ workshop_prefix }}-vpc_id"
vpc_route_path:                   "{{ deploy_working_dir }}/{{ workshop_prefix }}-vpc_route"
vpc_subnet_path:                  "{{ deploy_working_dir }}/{{ workshop_prefix }}-vpc_subnet"
vpc_rhel_ids_path:                "{{ deploy_working_dir }}/{{ workshop_prefix }}-vpc_rhel_ids"
ansible_ssh_private_key_file:     "{{ ssh_key_path }}"
system_user:                      "ec2-user"    # AWS
local_user:                       "{{ ansible_env.USERNAME | default( ansible_env.USER ) }}"
workshop:                         "container_security"
workshop_name:                    "{{ workshop }}"
workshop_abbrev:                  "cs" # the prefix for the type of workshop being run
