---
- debug:
    msg: "Configure CodeReady Workspaces for Ansible for user{{ item }}"

- name: Pause for 15 second between connections
  pause:
    seconds: 15

- name: Create workspace for user in CodeReady (user1)
  set_fact:
    max_retries: "{{ 40 if max_retries is undefined else max_retries | int }}"
  when: item  == "1"

- name: Create workspace for user in CodeReady (>user1)
  set_fact:
    max_retries: "{{ 5 if (max_retries == '40') else max_retries | int }}"
  when:  item >= "2"

- name: Create workspace for user in CodeReady
  block:
  - name: Increment the retry count
    set_fact:
      retry_count: "{{ 0 if retry_count is undefined else retry_count | int + 1 }}"
  - debug:
      msg: "max_retries = {{ max_retries }}, attempt = {{ retry_count }}"

  - name: "Request token via URI"
    uri:
      url: "https://keycloak-codeready-workspaces.apps.{{ openshift_cluster_fqdn }}/auth/realms/codeready/protocol/openid-connect/token"
      validate_certs: false
      method: POST
      body:
        username: "user{{ item }}"
        password: "{{ openshift_user_password }}"
        grant_type: "password"
        client_id: "admin-cli"
      body_format: form-urlencoded
      status_code: 200
    register: user_token
  - name: Create workspace from devfile
    uri:
      url: "https://codeready-codeready-workspaces.apps.{{ openshift_cluster_fqdn }}/api/workspace/devfile?start-after-create=true&namespace=user{{ item }}"
      validate_certs: false
      method: POST
      headers:
        Content-Type: application/json
        Authorization: "Bearer {{ user_token.json.access_token }}"
      body: "{{ lookup('url', 'https://raw.githubusercontent.com/matmille/che-ansible/main/devfile2.json', split_lines=False) }}"
      body_format: json
      status_code: 201,409
    register: workspace_def

  - name: Create user ssh-key secret
    community.kubernetes.k8s:
      state: present
      src: "{{ openshift_build_path }}/sshkey-user{{ item }}.yaml"

  rescue:
    - fail:
        msg: Maximum retries of grouped tasks reached
      when: retry_count | int == max_retries | int
    - debug:
        msg: "Unable to load devfile for user{{ item }} workspace- retry"
    - name: Pause for 2 second between connections
      pause:
        seconds: 2
    - include_tasks: usertoken.yml

- name: Increment the retry count
  set_fact:
    retry_count: 0
