# file: 2_load.yml
---
# https://www.terraform.io/docs/providers/aws/index.html

- name: Wait for AWS AMIs to become initialized
  hosts: localhost
  tasks:
    - wait_for:
        host: "{{ item }}"
        port: 22
        state: started
        timeout: 300
      with_items: "{{ groups.all_nodes }}"

- name: Configure repositories on nodes
  become: yes
  remote_user: ec2-user
  hosts: nodes
  roles:
    - { role: subscription_manager }
    - { role: epel }

- name: Configure LetsEncrypt on Specified Node
  become: yes
  remote_user: ec2-user
  hosts: le_node
  roles:
    - { role: LetsEncrypt }

- name: Configure software on nodes
  become: yes
  remote_user: ec2-user
  hosts: nodes
  roles:
    - { role: nodejs }
    - { role: wetty }
    - { role: zsh }

- name: Configure Cockpit
  become: yes
  remote_user: ec2-user
  hosts: nodes
  roles:
    - { role: cockpit }

- name: Upgrade packages
  become: yes
  remote_user: ec2-user
  hosts: nodes
  roles:
    - { role: upgrade }

...
