# file: site.yml
---

#---------------------------------------------------
# Terraform Providers
#---------------------------------------------------
- name: Terraform AWS Provider
  hosts: local_target
  roles:
    - { role: aws.infra.terraform, tags: ["terraform"], when: openshift_cloudprovider_kind == "aws" }

#---------------------------------------------------
# OpenShift Pre- Installation
#---------------------------------------------------
- name: OpenShift Pre- Installation
  hosts: masters, nodes
  become: yes
  roles:
    - { role: prereq.openshift, tags: ["atomic", "network", "rhel"] }

#---------------------------------------------------
# OpenShift Advanced Installation
#---------------------------------------------------
- name: OpenShift Advanced Installation
  hosts: masters
  roles:
    - { role: install.openshift, tags: ["advanced"] }

#---------------------------------------------------
# Configure OpenShift Cluster
#---------------------------------------------------
- name: Configure OpenShift Cluster
  hosts: masters
  become: yes
  roles:
    - { role: config.openshift, tags: ["administration"] }
