---
# tasks file for graphical
- when: graphical == 'true'
  block:

  - name: Gather package facts
    package_facts:
      manager: auto

  - name: Gather service facts
    service_facts:

  - name: RHEL 7 Tasks
    block:
    - name: Install GUI components (cloud access)
      yum:
        name:
        - "@gnome-desktop"
        - "@x11"
        - "@fonts"
        - "tigervnc-server"
        exclude: "fwupdate-efi"
        disablerepo: "*"
        enablerepo: "rhui-REGION-rhel-server-releases"
        skip_broken: "yes"
        state: present
      when: cloud_access

    - name: Install GUI components
      yum:
        name:
        - "@gnome-desktop"
        - "@x11"
        - "@fonts"
        - "tigervnc-server"
        exclude: "fwupdate-efi"
#        disablerepo: "*"
#        enablerepo: "rhel-7-server-rpms"
        skip_broken: "yes"
        state: present
      when: not cloud_access
  
    - name: Install XRDP server and dependencies
      yum:
        name:
        - "xrdp"
        - "xrdp-selinux"
        - "xorgxrdp"
#        disablerepo: "*"
#        enablerepo: "epel"
        state: present

    when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '7'

  - name: RHEL 8 Tasks
    block:

    - name: Make sure using latest version of dnf
      yum:
        name: "dnf"
        state: latest

    - name: Install GUI components and Xrdp build reqs on RHEL 8
#      command: yum -y install @graphical-server-environment tigervnc-server 'xorg-*' coreutils wget --skip-broken
      yum:
        name:
#        - "@Server with GUI"
##        - "@^Server with GUI"
        - '@graphical-server-environment'
        - tigervnc-server
        - "xorg-*"
        - coreutils
        - wget
##        exclude:
##        - fwupdate-efi
##        - file-roller-nautilus
#        skip_broken: "yes"
        state: present
  
    - name: Install XRDP server and dependencies
      yum:
        name:
        - "xrdp"
        - "xrdp-selinux"
        - "xorgxrdp"
#        disablerepo: "*"
#        enablerepo: "epel"
        state: present

# Commented out due to the addition of Xrdp/xorgxdp to EPEL 8
#    - name: Install build tools and headers
#      yum:
#        name:
#        - nasm
#        - xorg-x11-server-devel
#        enablerepo: codeready-builder-for-rhel-8-x86_64-rpms

#    - name: Create build directory
#      file:
#        path: "/home/ec2-user/src"
#        state: directory
#      become: false

#    - name: Clone xrdp repo
#      git:
#        repo: "https://github.com/neutrinolabs/xrdp"
#        dest: "/home/ec2-user/src/xrdp"
#        recursive: true
#      become: false

#    - name: Bootstrap xrdp
#      command: "./bootstrap"
#      args:
#        chdir: "/home/ec2-user/src/xrdp"
#        creates: "/home/ec2-user/src/xrdp/depcomp"
#      become: false

#    - name: Configure xrdp
#      command: "./configure"
#      args:
#        chdir: "/home/ec2-user/src/xrdp"
#        creates: "/home/ec2-user/src/xrdp/Makefile"
#      become: false

#    - name: Make xrdp
#      make:
#        chdir: "/home/ec2-user/src/xrdp"
#        target: "all"
#      become: false

#    - name: Make install xrdp
#      make:
#        chdir: "/home/ec2-user/src/xrdp"
#        target: "install"

#    - name: Clone xorgxrdp repo
#      git:
#        repo: "https://github.com/neutrinolabs/xorgxrdp"
#        dest: "/home/ec2-user/src/xorgxrdp"
#        recursive: true
#      become: false

#    - name: Bootstrap xorgxrdp
#      command: "./bootstrap"
#      args:
#        chdir: "/home/ec2-user/src/xorgxrdp"
#        creates: "/home/ec2-user/src/xorgxrdp/depcomp"
#      become: false

#    - name: Configure xorgxrdp
#      command: "./configure PKG_CONFIG_PATH=/usr/local/lib/pkgconfig"
#      args:
#        chdir: "/home/ec2-user/src/xorgxrdp"
#        creates: "/home/ec2-user/src/xorgxrdp/Makefile"
#      become: false

#    - name: Make xorgxrdp
#      make:
#        chdir: "/home/ec2-user/src/xorgxrdp"
#        target: "all"
#      become: false

#    - name: Make install xorgxrdp
#      make:
#        chdir: "/home/ec2-user/src/xorgxrdp"
#        target: "install"

    - name: Install Xwrapper configuration
      copy:
        dest: "/etc/X11/Xwrapper.config"
        src: "Xwrapper.config"
        mode: 0644

    when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '8'

  - name: Install xrdp configuration
    copy:
      dest: "/etc/xrdp/xrdp.ini"
      src: "xrdp.ini"
      mode: 0644

  - name: Create SELinux dir
    file:
      group: "{{ system_user }}"
      owner: "{{ system_user }}"
      mode:  0700
      path:  "/home/{{ system_user }}/.selinux"
      state: directory

  - name: Copy over SELinux modules for colord
    copy:
      src:   "{{ item }}"
      dest:  "/home/{{ system_user }}/.selinux"
      group: "{{system_user}}"
      owner: "{{system_user}}"
      mode:  0600
    with_items:
      - colord-add.pp
      - colord-add.te
    register: result

  - name: Copy over polikt config for colord
    copy:
      src:   "02-allow-colord.rules"
      dest:  "/etc/polkit-1/rules.d/02-allow-colord.rules"
      group: "root"
      owner: "root"
      mode:  0644

  - name: Update SELinux for colord
    command: semodule -i colord-add.pp chdir=/home/{{ system_user }}/.selinux
    notify: colord
    when: result.changed

  - when: ansible_facts.packages["firewalld"] is defined
    block:
  
    - name: open XRDP port in firewalld (permanent)
      firewalld:
        port: "3389/tcp"
        state: enabled
        permanent: yes
  
    - name: open XRDP port in firewalld (immediate)
      firewalld:
        port: "3389/tcp"
        state: enabled
        immediate: yes
      when: ansible_facts.services["firewalld.service"].state == "running"
    
  - when: ansible_facts.packages["firewalld"] is undefined
    block:

    - name: open XRDP port in iptables
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 3389
        jump: ACCEPT
      when: ansible_facts.services["firewalld.service"].state == "running"

  - name: Enable XRDP auto-start
    service:
      name: "xrdp"
      enabled: "yes"
      state: started

...
