# file: 3_unregister.yml
---

# Do not use with Cloud Access
- name: Unregister Nodes 
  become: yes
  gather_facts: false
  ignore_errors: true
  hosts:
    - rhel_nodes
  remote_user: ec2-user
  roles:
    - role: unregister
      when: NOSSH is undefined

- name: Remove infrastructure
  hosts: localhost
  connection: local
  roles:
  - { role: aws.remove, tags: ["delete"] }

...
