# file: group_vars/all.yml

#####################################################
# Default configuration
#####################################################
default_domain:    "{{ vault_default_domain }}"
default_subdomain: "{{ vault_cluster_name }}.{{ default_domain }}"
default_wildcard:  "apps.{{ default_subdomain }}"
default_user:      "ec2-user"
default_home:      "/home/{{ default_user }}"
default_ssh:       "{{ default_home }}/.ssh"
default_keypair:   "{{ vault_cluster_name }}"
number_nodes:      "{{ vault_number_nodes }}"
master_size:       "{{ vault_master_size }}"
node_size:         "{{ vault_node_size }}"
ami:               "{{ vault_ami }}"
redhat_uid:        "{{ vault_redhat_uid }}"
redhat_pwd:        "{{ vault_redhat_pwd }}"
rhsm_username:     "{{ vault_redhat_uid }}"
rhsm_password:     "{{ vault_redhat_pwd }}"
rhsm_pool_id:      "{{ vault_rhsm_pool_id }}"

#####################################################
# AWS access keys
#####################################################
aws_access_key_id:     "{{ vault_aws_access_key_id }}"
aws_secret_access_key: "{{ vault_aws_secret_access_key }}"
region:                "us-east-1"

#####################################################
# Terraform configuration
#####################################################
terraform_working_dir:                 "{{ lookup('env','PWD') }}/.redhatgov"
terraform_provisioner_connection_type: "ssh"

#####################################################
# Docker configuration
#####################################################
os_docker_block_device: "/dev/xvdb"
os_docker_volume_group: "docker-vg"
os_docker_vol_size:     "50"
os_docker_vol_type:     "gp2"

#####################################################
# OpenShift configuration
#####################################################
openshift_release:             "{{ vault_openshift_release }}"
openshift_cluster_name:        "{{ vault_cluster_name }}"
openshift_cluster_id:          "{{ vault_cluster_id }}"
openshift_test_users_count:    "{{ vault_users_count }}"
openshift_test_users_password: "{{ vault_openshift_cluster_admin_password }}"

#####################################################
# Ansible configuration
#####################################################
ansible_user:                 "{{ default_user }}"
ansible_ssh_private_key_file: "{{ terraform_working_dir }}/{{ default_keypair }}"
inventory_working_dir:        "{{ lookup('env','PWD') }}/inventory"

#####################################################
# Wetty configuration
#####################################################
system_user:       ec2-user
letsencrypt:       false
domain_name:       "{{ vault_default_domain }}"
workshop_password: "{{ vault_openshift_cluster_admin_password }}"
