# file: group_vars/all.yml

#####################################################
# Default configuration
#####################################################
default_domain: "{{ vault_default_domain }}"
default_subdomain: "ocp.{{ default_domain }}"
default_wildcard: "apps.{{ default_subdomain }}"
default_user: "ec2-user"
default_home: "/home/{{ default_user }}"
default_ssh: "{{ default_home }}/.ssh"
default_keypair: "{{ vault_default_keypair }}"

#####################################################
# AWS access keys
#####################################################
aws_access_key_id: "{{ vault_aws_access_key_id }}"
aws_secret_access_key: "{{ vault_aws_secret_access_key }}"

#####################################################
# Terraform configuration
#####################################################
terraform_workspace: "{{ lookup('env','PWD') }}/.{{ default_domain }}"
terraform_provisioner_connection_type: "ssh"

#####################################################
# Docker configuration
#####################################################
os_docker_block_device: "/dev/xvdb"
os_docker_volume_group: "docker-vg"
os_docker_vol_size: "50"
os_docker_vol_type: "gp2"

#####################################################
# OpenShift configuration
#####################################################
openshift_release: "3.5"

#####################################################
# Ansible configuration
#####################################################
ansible_user: "{{ default_user }}"
ansible_ssh_private_key_file: "{{ terraform_workspace }}/{{ default_keypair }}"
