# file: 3_load.yml
---

- name: Wait for AWS AMIs to become initialized
  hosts: localhost
  gather_facts: no
  tasks:
    - wait_for:
        host: "{{ item }}"
        port: 22
        state: started
        timeout: 300
      with_items:
        - "{{ groups.rhel_nodes }}"
        - "{{ groups.tower_rhel_nodes }}"

- name: Configure repositories on all RHEL nodes
  become: yes
  remote_user: ec2-user
  hosts:
    - tower_rhel_nodes
    - rhel_nodes
  gather_facts: yes
  roles:
    - role: subscription_manager 
    - role: firewalld

- name: Configure epel on tower nodes
  become: yes
  remote_user: ec2-user
  hosts: tower_rhel_nodes
  roles:
    - role: epel

- name: Remove Red Hat EAP packages
  become: yes
  remote_user: ec2-user
  hosts:
    - tower_rhel_nodes
    - rhel_nodes
  gather_facts: no
  tasks:
    - package:
        name: eap7-*
        state: absent
      when: jboss|bool
      ignore_errors: yes

- name: Configure repositories on nodes
  become: yes
  remote_user: ec2-user
  hosts: le_node
  gather_facts: no
  roles:
    - role: LetsEncrypt
    
- name: Ensure python3-pip installed for powerline (RHEL 8)
  become: yes
  remote_user: ec2-user
  hosts: tower_rhel_nodes
  gather_facts: no
  tasks:
    - package:
        name: python3-pip
        state: latest
      when: rhel_ver == 'rhel8'    

- name: Configure software on nodes
  become: yes
  remote_user: ec2-user
  hosts: tower_rhel_nodes
  gather_facts: no
  roles:
    - role: nodejs
    - role: ansible.tower
    - role: system-user
    - role: powerline
    - role: vscode
      when: graphical|bool
    - role: graphical
      when: graphical|bool
    - role: code-server
      code_pass: "{{ workshop_password }}"
  tasks:
    - name: push out student templates
      copy:
        src: "{{ item }}"
        dest: "~{{ system_user }}/{{ item }}"
        mode: 0644
      with_items:
      - "hello.js"
      - "hello.service"

- name: Configure web console (RHEL 7)
  become: yes
  remote_user: ec2-user
  hosts: tower_rhel_nodes
  gather_facts: no
  roles:
    - role: wetty
      when: rhel_ver == 'rhel7'

- name: Configure web console (RHEL 8)
  become: yes
  remote_user: ec2-user
  hosts: tower_rhel_nodes
  gather_facts: no
  roles:
    - role: cockpit
      when: rhel_ver == 'rhel8'

- name: Stage Maven POMs
  become: yes
  remote_user: ec2-user
  hosts: rhel_nodes
  gather_facts: yes
  roles:
    - role: poms
      when: jboss|bool

- name: Upgrade packages
  become: yes
  remote_user: ec2-user
  hosts:
    - tower_rhel_nodes
    - rhel_nodes
  roles:
    - role: upgrade

- name: Re-enable SCL repo when upgrade disables it
  become: yes
  remote_user: ec2-user
  hosts:
    - tower_rhel_nodes
    - rhel_nodes
  gather_facts: yes
  roles:
    - role: subscription_manager 

- name: Open ports 80,443 on nodes
  become: yes
  remote_user: ec2-user
  hosts:
    - rhel_nodes
  gather_facts: yes
  tasks:
    - name: open firewalld ports
      firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
      with_items:
      - 'http'
      - 'https'
    - name: restart service
      service:
        name: firewalld
        state: reloaded

...
