# file: 2_load.yml
---

- name: Wait for AWS AMIs to become initialized
  hosts: localhost
  gather_facts: no
  tasks:
    - wait_for:
        host: "{{ item }}"
        port: 22
        state: started
        timeout: 300
      with_items:
        - "{{ groups.rhel_nodes }}"
        - "{{ groups.tower_rhel_nodes }}"

- name: Configure repositories on all RHEL nodes
  become: yes
  remote_user: ec2-user
  hosts:
    - tower_rhel_nodes
    - rhel_nodes
  gather_facts: yes
  roles:
    - role: subscription_manager 

- name: Configure epel on tower nodes
  become: yes
  remote_user: ec2-user
  hosts: tower_rhel_nodes
  tasks:
    - name: RHEL 8 on AWS via Cloud Access has no available repositories
      fail:
        msg: "Please use RHSM via user ID/password or org ID/activation key."
      when: cloud_access and ansible_distribution == 'RedHat' and ansible_distribution_major_version == '8'
  roles:
    - role: epel

- name: Remove Red Hat EAP packages
  become: yes
  remote_user: ec2-user
  hosts:
    - tower_rhel_nodes
    - rhel_nodes
  gather_facts: no
  tasks:
    - package:
        name: eap7-*
        state: absent
      when: jboss is defined
      ignore_errors: yes

- name: Configure repositories on nodes
  become: yes
  remote_user: ec2-user
  hosts: le_node
  gather_facts: no
  roles:
    - role: LetsEncrypt

- name: Configure software on nodes
  become: yes
  remote_user: ec2-user
  hosts: tower_rhel_nodes
  gather_facts: no
  roles:
    - role: nodejs
    - role: ansible.tower
    - role: vscode
    - role: graphical
    - role: system-user

- name: Configure web console (RHEL 7)
  become: yes
  remote_user: ec2-user
  hosts: tower_rhel_nodes
  gather_facts: no
  roles:
    - role: wetty
      when: rhel_ver == 'rhel7'

- name: Configure web console (RHEL 8)
  become: yes
  remote_user: ec2-user
  hosts: tower_rhel_nodes
  gather_facts: no
  roles:
    - role: cockpit
      when: rhel_ver == 'rhel8'

- name: Stage Maven POMs
  become: yes
  remote_user: ec2-user
  hosts: rhel_nodes
  gather_facts: yes
  roles:
    - role: poms
      when: jboss is defined

- name: Upgrade packages
  become: yes
  remote_user: ec2-user
  hosts:
    - tower_rhel_nodes
    - rhel_nodes
  roles:
    - role: upgrade

- name: Re-enable SCL repo when upgrade disables it
  become: yes
  remote_user: ec2-user
  hosts:
    - tower_rhel_nodes
    - rhel_nodes
  gather_facts: yes
  roles:
    - role: subscription_manager 

...
