# file: roles/terraform.infra.aws/tasks/terraform.yml
---

- name: Remove existing key pair
  ec2_key: name="{{ default_keypair }}" region="{{ aws_route53_region }}" state=absent

- name: Create new key pair
  ec2_key: name="{{ default_keypair }}" region="{{ aws_route53_region }}" state=present
  register: ec2_key

- debug: var=ec2_key

- name: Create workspace
  file: path="{{ terraform_workspace }}"  state=directory

- name: Copy new key pair to workspace
  copy:
    content: "{{ ec2_key.key.private_key }}"
    dest: "{{ terraform_workspace }}/{{ default_keypair }}"
    mode: 0400

- name: Create Terraform template
  template: dest="{{ terraform_workspace }}/aws.tf" src=aws.tf.j2

- name: Create user data template
  template: dest="{{ terraform_workspace }}/init.tpl" src=init.tpl.j2

- name: Terraform apply (build/change infrastructure)
  command: terraform apply chdir="{{ terraform_workspace }}"

- name: Wait for host initialization
  pause: minutes=4
