# file: roles/LetsEncrypt/tasks/main.yml
---
- name: Install Certbot Repos
  become: yes
  yum:
    name:  "{{ item }}"
    state: present  
  with_items:
    - yum-utils
  when: letsencrypt

- name: Install Certbot
  become: yes
  yum:
    name: "certbot" 
    enablerepo: "{{ item }}"
    state: present
  with_items:
    - rhui-REGION-rhel-server-extras
    - rhui-REGION-rhel-server-optional
  when: letsencrypt 

- debug: 
    var: hostvars[inventory_hostname]['ec2_tag_Index']
  when: letsencrypt

- name: Generate Certs tower-node
  become: yes
  command: certbot certonly --standalone \
                            --agree-tos  \
                            --non-interactive \
                            --text \
                            --rsa-key-size 4096 \
                            --email {{ letsencrypt_email }} \
                            --domains "{{ workshop_prefix | lower }}.tower.{{ hostvars[inventory_hostname]['ec2_tag_Index'] }}.{{ domain_name }}"
  when: letsencrypt

# New certs located at:  /etc/letsencrypt/live/<url>/

