---

- name: Provision AWS Infrastructure
  hosts: localhost
  connection: local
  gather_facts: False
  roles:
  - setup-key
  - setup-vpc
  - setup-security-groups
  - setup-virtual-machines
  - setup-dns
  - setup-ssh
  - setup-host-groups
  pre_tasks:
    - name: Verify Ansible Version
      assert:
        that:
          - "ansible_version.major == 2"
          - "ansible_version.minor == 4"
        msg: "This script is only supported with the 2.4 version of Ansible"
    - fail: msg="Variable '{{ item }}' is not defined or is empty"
      when: (platform == 'openshift-enterprise') and ((item not in vars) or vars[item] == '')
      with_items:
        # - rhsm_username
        # - rhsm_password
        # - rhsm_pool
        - rhsm_key_id
        - rhsm_org_id

# [TODO]: Create a 'action_plugin/sethosts.py' that updates 'inventory/hosts'
# file with 'ec2_master_tag', 'ec2_bastion_tag', 'created_vms', and
# 'created_nodes' groups that are stored in session from 'setup-host-groups' in
# role above.

- name: Setup VM hosts
  hosts: localhost

- name: Register and update virtual machines
  hosts: created_vms
  remote_user: "{{ remote_user_name }}"
  vars:
    state: 'present'
  roles:
  - {role: register-virtual-machines, when: platform == 'openshift-enterprise'}
  - update-virtual-machines

- name: Setup Node hosts
  hosts: localhost

- name: OpenShift Prerequisites
  hosts: created_nodes
  remote_user: "{{ remote_user_name }}"
  vars:
    state: 'present'
  roles:
  - openshift-prep-install

- name: Install OpenShift
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    # nodes_ip: "{{ lookup('file','nodes.json') | from_json }}"
    state: 'present'
  roles:
  - openshift-install
  post_tasks:
   - name: Confirmation message
     debug:
      msg:
        - 'The script has completed successfully.'
        - 'Master public IP: {{ master_public_ip }}'
        - 'OpenShift console: https://{{ domain }}:8443'
