---
- name: Install Java 1.7 and some basic dependencies
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
   - unzip
   - java-1.7.0-openjdk
   - libselinux-python
   - libsemanage-python

- name: Copy Windup archive
  become: yes
  copy:
    dest: "/tmp/"
    group: "{{ system_user }}"
    owner: "{{ system_user }}"
    mode: 0700
    src: "jboss-migrationtoolkit-windup-2.7.0.GA.zip" 

- name: Extract Windup archive
  unarchive: 
    remote_src: true
    dest: /home/{{ system_user }}
    src: /tmp/jboss-migrationtoolkit-windup-2.7.0.GA.zip
    creates: /home/{{ system_user }}/migrationtoolkit-windup

- name: Copy JMT Console archive
  become: yes
  copy:
    dest: "/home/{{ system_user }}/lab2/"
    group: "{{ system_user }}"
    owner: "{{ system_user }}"
    mode: 0700
    src: "jee-example-app-1.0.0.ear" 

