---

- name: Provision Tower servers
  os_server:
    state: "present"
    name: "{{ workshop_prefix }}-tower-{{ item.name }}"
    image: "RHEL 7.5 (RHN) [BYOL]"
    key_name: "{{ workshop_prefix }}-student-key"
    flavor: "t1.medium"
    network: "{{ workshop_prefix }}-student-network"
    floating_ip_pools: external-floating-ips
    timeout: 200
    security_groups:
      - default
      - "{{ workshop_prefix }}-student-fw"
  with_items: "{{ tower_server_defaults }}"
  register: tower_nodes

# - debug:
#     var: tower_nodes.results[0].changed
#   ignore_errors: true

# AWS Route53 DNS: TOWER NODE
- name: Create DNS names for Tower Nodes
  route53: 
    command: create
    zone:   "{{ domain_name }}"
    record: "{{ workshop_prefix }}.tower.{{ item[0] }}.{{ domain_name }}" #example.tower.0.redhatgov.io
    type: A
    ttl: 300
    value:  "{{ item[1].openstack.accessIPv4 }}"
    overwrite: yes
    wait: yes
  with_indexed_items: "{{ tower_nodes.results }}"


- name: Create Ansible-managed instance
  os_server:
    state: "present"
    name: "{{ workshop_prefix }}-managed-node-{{ item.name }}"
    image: "RHEL 7.5 (RHN) [BYOL]"
    key_name: "{{ workshop_prefix }}-student-key"
    flavor: "t1.medium"
    network: "{{ workshop_prefix }}-student-network"
    floating_ip_pools: external-floating-ips
    timeout: 200
    security_groups:
      - default
      - "{{ workshop_prefix }}-student-fw"
  with_items: "{{ tower_node_defaults }}"
  register: managed_nodes

# # AWS Route53 DNS: MANAGED NODE
- name: Create DNS names for Managed Nodes
  route53: 
    command: create
    zone:   "{{ domain_name }}"
    record: "{{ workshop_prefix }}.node.{{ item[0] }}.{{ domain_name }}" #example.tower.0.redhatgov.io
    type: A
    ttl: 300
    value:  "{{ item[1].openstack.accessIPv4 }}"
    overwrite: yes
    wait: yes
  with_indexed_items: "{{ managed_nodes.results }}"

 