---
- name: Check if EPEL repo is already configured.
  stat: path={{ epel_repofile_path }}
  register: epel_repofile_result

- name: Install EPEL GPG Key
  command: rpm --import http://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7

- name: Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  until: 'result.rc == 0'
  retries: 5
  delay: 10
  when: not epel_repofile_result.stat.exists

# - name: Import EPEL GPG key.
#   rpm_key:
#     key: "{{ epel_repo_gpg_key_url }}"
#     state: present
#   when: not epel_repofile_result.stat.exists
#   ignore_errors: "{{ ansible_check_mode }}"