---
# tasks file for roles/aws.remove

- name: RHEL AMI
  debug:
    msg: "Using AWS {{ region }} {{ rhel_ver }} AMI: {{ regions[region][rhel_ver].ami }}"

- name: Windows AMI
  debug:
    msg: "Using AWS {{ region }} {{ win_ver }} AMI: {{ regions[region][win_ver].ami }}"

- debug:
    var: tower_instance_type

- debug:
    var: bastion_instance_type
  when: workshop == "container_security"

- debug:
    var: rhel_instance_type

- debug:
    var: win_instance_type

- name: define container_security required racts
  set_fact:
    rhel_count: "{{ student_count|int*student_nodes_count|int }}"
  when: workshop == "container_security"

#===============================================================================
#  Search and record IDs
#===============================================================================
- name: Initialize an empty list for our strings
  set_fact:
    route_id: ""
    subnet_id: ""
    vpc_id: ""
    admin_rhel_instance_ids: []
    tower_rhel_instance_ids: []
    bastion_rhel_instance_ids: []
    rhel_instance_ids: []
    rhel_group_id: ""
    win_instance_ids: []
    win_group_id: ""

- name: lookup running RHEL admin instances
  ec2_instance_info:
    region: "{{ region }}"
    filters:
      tag:rhel_admin: "{{ workshop_abbrev }}-{{ workshop_prefix }}"
  register: ec2_rhel_admin

- name: lookup running RHEL instances
  ec2_instance_info:
    region: "{{ region }}"
    filters:
      tag:rhel: "{{ workshop_abbrev }}-{{ workshop_prefix }}"
  register: ec2_rhel

- name: lookup running RHEL bastion instances
  ec2_instance_info:
    region: "{{ region }}"
    filters:
      tag:bastion_rhel: "{{ workshop_abbrev }}-{{ workshop_prefix }}"
  register: ec2_bastion_rhel

- name: lookup running RHEL Tower instances
  ec2_instance_info:
    region: "{{ region }}"
    filters:
      tag:tower_rhel: "{{ workshop_abbrev }}-{{ workshop_prefix }}"
  register: ec2_tower_rhel

- debug:
    var: ec2_rhel

- debug:
    var: ec2_tower_rhel

- name: Append RHEL admin instances to list
  set_fact:
    admin_rhel_instance_ids: "{{ admin_rhel_instance_ids }} + [ '{{ item.instance_id }}' ]"
  with_items: "{{ ec2_rhel_admin.instances }}"

- name: Append RHEL instances to list
  set_fact:
    rhel_instance_ids: "{{ rhel_instance_ids }} + [ '{{ item.instance_id }}' ]"
  with_items: "{{ ec2_rhel.instances }}"

- name: Append RHEL Tower instances to list
  set_fact:
    tower_rhel_instance_ids: "{{ tower_rhel_instance_ids }} + [ '{{ item.instance_id }}' ]"
  with_items: "{{ ec2_tower_rhel.instances }}"

- name: Append RHEL bastion instances to list
  set_fact:
    bastion_rhel_instance_ids: "{{ bastion_rhel_instance_ids }} + [ '{{ item.instance_id }}' ]"
  with_items: "{{ ec2_bastion_rhel.instances }}"

- name: lookup running Windows instances
  ec2_instance_info:
    region: "{{ region }}"
    filters:
      tag:win: "{{ workshop_abbrev }}-{{ workshop_prefix }}"
  register: ec2_win

- name: Append Windows instances to list`
  set_fact:
    win_instance_ids: "{{ win_instance_ids }} + [ '{{ item.instance_id }}' ]"
  with_items: "{{ ec2_win.instances }}"

- name: lookup running windows security groups
  ec2_group_info:
    region: "{{ region }}"
    filters:
      tag:win: "{{ workshop_abbrev }}-{{ workshop_prefix }}"
  register: ec2_win_grp

- name: Record Windows security group ID
  set_fact:
    win_group_id: "{{ ec2_win_grp.security_groups[0].group_id }}"
  when: ec2_win_grp.security_groups|length > 0

- name: lookup running rhel security groups
  ec2_group_info:
    region: "{{ region }}"
    filters:
      tag:rhel: "{{ workshop_abbrev }}-{{ workshop_prefix }}"
  register: ec2_rhel_grp

- name: Record RHEL security group ID
  set_fact:
    rhel_group_id: "{{ ec2_rhel_grp.security_groups[0].group_id }}"
  when: ec2_rhel_grp.security_groups|length > 0

- name: lookup running subnets
  ec2_vpc_subnet_info:
    region: "{{ region }}"
    filters:
      tag:workshop: "{{ workshop }}"
      tag:workshop_prefix: "{{ workshop_prefix }}"
  register: ec2_subnet

- name: Record subnet ID
  set_fact:
    subnet_id: "{{ ec2_subnet.subnets[0].subnet_id }}"
  when: ec2_subnet.subnets|length > 0

- name: lookup running vpc route tables
  ec2_vpc_route_table_info:
    region: "{{ region }}"
    filters:
      tag:workshop: "{{ workshop }}"
      tag:workshop_prefix: "{{ workshop_prefix }}"
  register: ec2_route

- name: Record route table ID 
  set_fact:
    route_id: "{{ ec2_route.route_tables[0].id }}"
  when: ec2_route.route_tables|length > 0

- name: lookup running vpcs
  ec2_vpc_net_info:
    region: "{{ region }}"
    filters:
      tag:workshop: "{{ workshop }}"
      tag:workshop_prefix: "{{ workshop_prefix }}"
  register: ec2_vpc

- name: Record VPC ID
  set_fact:
    vpc_id: "{{ ec2_vpc.vpcs[0].id }}"
  when: ec2_vpc.vpcs|length > 0

#===============================================================================
#  Deprovisioning
#===============================================================================

- name: Lookup existing DNS records
  community.aws.route53:
    state: get
    zone: "{{ domain_name }}"
    record: "{{ item }}"
    type: "CNAME"
  register: recs
  with_inventory_hostnames:
    - all:!localhost

- debug:
    var: recs

- name: Remove existing DNS records
  route53:
    state: absent
    zone: "{{ domain_name }}"
    record: "{{ item.set.record }}"
    ttl: "{{ item.set.ttl }}"
    type: "{{ item.set.type }}"
    value: "{{ item.set.value }}"
  when: item.set.record is defined
  loop: "{{ recs[ 'results' ] }}"

- name: Remove Windows instances
  ec2:
    key_name: "{{ workshop_abbrev }}-{{ workshop_prefix }}-key"
    group: "{{ workshop_abbrev }}-{{ workshop_prefix }}-win-sg"
    region: "{{ region }}"
    instance_type: "{{ win_instance_type }}"
    image: "{{ regions[region][win_ver].ami }}"
    vpc_subnet_id: "{{ subnet_id }}"
    wait: true
    instance_ids: "{{ win_instance_ids }}"
    state: absent
  when: win_instance_ids|length > 0

- name: Remove RHEL Tower instances
  ec2:
    key_name: "{{ workshop_abbrev }}-{{ workshop_prefix }}-key"
    group: "{{ workshop_abbrev }}-{{ workshop_prefix }}-rhel-sg"
    region: "{{ region }}"
    instance_type: "{{ tower_instance_type }}"
    image: "{{ regions[region][rhel_ver].ami }}"
    vpc_subnet_id: "{{ subnet_id }}"
    wait: true
    instance_ids: "{{ tower_rhel_instance_ids }}"
    state: absent
  when: tower_rhel_instance_ids|length > 0
    #  when: false

- name: Remove RHEL admin instances
  ec2:
    key_name: "{{ workshop_abbrev }}-{{ workshop_prefix }}-key"
    group: "{{ workshop_abbrev }}-{{ workshop_prefix }}-rhel-sg"
    region: "{{ region }}"
    instance_type: "{{ rhel_instance_type }}"
    image: "{{ regions[region][rhel_ver].ami }}"
    vpc_subnet_id: "{{ subnet_id }}"
    wait: true
    instance_ids: "{{ admin_rhel_instance_ids }}"
    state: absent
  when: admin_rhel_instance_ids|length > 0

- name: Remove RHEL bastion instances
  ec2:
    key_name: "{{ workshop_abbrev }}-{{ workshop_prefix }}-key"
    group: "{{ workshop_abbrev }}-{{ workshop_prefix }}-rhel-sg"
    region: "{{ region }}"
    instance_type: "{{ bastion_instance_type }}"
    image: "{{ regions[region][rhel_ver].ami }}"
    vpc_subnet_id: "{{ subnet_id }}"
    wait: true
    instance_ids: "{{ bastion_rhel_instance_ids }}"
    state: absent
  when: bastion_rhel_instance_ids|length > 0

- name: Remove RHEL instances
  ec2:
    key_name: "{{ workshop_abbrev }}-{{ workshop_prefix }}-key"
    group: "{{ workshop_abbrev }}-{{ workshop_prefix }}-rhel-sg"
    region: "{{ region }}"
    instance_type: "{{ rhel_instance_type }}"
    image: "{{ regions[region][rhel_ver].ami }}"
    vpc_subnet_id: "{{ subnet_id }}"
    wait: true
    instance_ids: "{{ rhel_instance_ids }}"
    state: absent
  when: rhel_instance_ids|length > 0

- name: Delete VPC route table
  ec2_vpc_route_table:
    region: "{{ region }}"
    vpc_id: "{{ vpc_id }}"
    lookup: id
    route_table_id: "{{ route_id }}"
    state: absent

- name: Delete public subnet
  ec2_vpc_subnet:
    region: "{{ region }}"
    cidr: "10.0.2.0/24"
    vpc_id: "{{ vpc_id }}"
    state: absent

- name: Delete private subnet
  ec2_vpc_subnet:
    region: "{{ region }}"
    cidr: "10.0.3.0/24"
    vpc_id: "{{ vpc_id }}"
    state: absent

- name: Delete Windows security group
  ec2_group:
    name: "{{ workshop_abbrev }}-{{ workshop_prefix }}-win-sg"
    region: "{{ region }}"
    state: absent

- name: Delete RHEL security group
  ec2_group:
    name: "{{ workshop_abbrev }}-{{ workshop_prefix }}-rhel-sg"
    region: "{{ region }}"
    state: absent

- name: Delete VPC internet gateway
  ec2_vpc_igw:
    region: "{{ region }}"
    vpc_id: "{{ vpc_id }}"
    state: absent

- name: Delete VPC
  ec2_vpc_net:
    name: "{{ workshop_abbrev }}-{{ workshop_prefix }}-vpc"
    region: "{{ region }}"
    cidr_block: "10.0.0.0/16"
    state: absent

- name: Delete key
  ec2_key:
    name: "{{ workshop_abbrev }}-{{ workshop_prefix }}-key"
    region: "{{ region }}"
    state: absent

...
