---

- name: Vagrant | Install & Configure Instances
  hosts: vagrant
  hosts: all 
  become: yes
  roles:
    - subscription_manager
    - openshift_templates
    - atomic_scanner_plugins
    - container_check_stp
    - docker
    - jq
    - skopeo
    - epel
    - cockpit
    - zsh
    - oc 


