---
# tasks file for roles/aws.create
#===============================================================================
#  Provisioning
#===============================================================================

- name: Find latest RHEL AMI
  shell:
    cmd: aws ec2 describe-images --owners 309956199498 --region "{{ region }}" --filters "Name=architecture,Values=x86_64" --filters "Name=name,Values={{ rhel_ver }}*x86_64*{{ 'Access2' if cloud_access == true else 'Hourly2' }}*" --query 'Images[*].[Name,ImageId]' --output text  | sort -V | awk '$1 !~ /.*BETA.*/ && $1 !~ /.*GA.*/ {ami=$2} END{print ami}'
  register: rhel_ami

- name: Find latest Windows Server AMI
  shell:
    cmd: aws ec2 describe-images --region "{{ region }}" --filters "Name=architecture,Values=x86_64" --filters "Name=name,Values={{ win_ver }}-English-Full-Base*" --query 'Images[*].[Name,ImageId]' --output text  | sort -V | awk '$1 !~ /.*BETA.*/ {ami=$2} END{print ami}'
  register: windows_ami

- name: RHEL AMI
  debug:
    msg: "Using AWS {{ region }} {{ rhel_ver }} AMI: {{ rhel_ami.stdout if auto_ami == true else regions[region][rhel_ver].ami }}"

- name: Windows AMI
  debug:
    msg: "Using AWS {{ region }} {{ win_ver }} AMI: {{ windows_ami.stdout if auto_ami == true else regions[region][win_ver].ami }}"

- name: deploy container security workshop
  block:
    - name: create DNS name list
      shell: "files/dns-list-create.sh {{ student_nodes_count }} {{ student_count }} {{ domain_name }} {{ workshop_prefix }}"
      register: dns_name_list

    - debug:
        var: dns_name_list

    - name: define container_security required racts
      set_fact:
        rhel_count: "{{ student_count|int*student_nodes_count|int }}"

  when: workshop == "container_security"

#---------------------------------------------------
#  Deployment directory creation
#---------------------------------------------------
- name: Make temporary location to run deployment
  file:
    path: "{{ deploy_working_dir }}"
    state: directory

#---------------------------------------------------
#  WinRM templating
#---------------------------------------------------
- name: Template Windows WinRM configuration
  template:
    dest: "{{ winrm_path }}"
    src: "winrm.txt.j2"

#---------------------------------------------------
#  EC2 INI Creation
#---------------------------------------------------
- name: Template EC2 INI File
  template: dest="{{ inventory_working_dir }}/ec2.ini"  src=ec2.ini.j2
  when: execution is defined

#---------------------------------------------------
#  SSH Key
#---------------------------------------------------
- name: Create EC2 keypair
  ec2_key:
    name: "{{ workshop_abbrev }}-{{ workshop_prefix }}-key"
    region: "{{ region }}"
    state: present
  register: ec2_key

- debug:
    var: ec2_key

- name: Create ssh keypair
  copy:
    content: "{{ ec2_key.key.private_key }}\n"
    dest: "{{ ssh_key_path }}"
    mode: 0400
  when: ec2_key.changed

#---------------------------------------------------
#  Create AWS objects
#---------------------------------------------------
- name: Create VPC
  ec2_vpc_net:
    name: "{{ workshop_abbrev }}-{{ workshop_prefix }}-vpc"
    region: "{{ region }}"
    cidr_block: "10.0.0.0/16"
    dns_hostnames: yes
    dns_support: yes
    tags:
      username: "{{ local_user }}"
      workshop: "{{ workshop }}"
      workshop_prefix: "{{ workshop_prefix }}"
    state: present
  register: ec2_vpc

- debug:
    var: ec2_vpc

- name: Create VPC internet gateway
  ec2_vpc_igw:
    region: "{{ region }}"
    vpc_id: "{{ ec2_vpc.vpc.id }}"
    state: present
    tags:
      Name: "{{ workshop_abbrev }}-{{ workshop_prefix }}-igw"
      username: "{{ local_user }}"
      workshop: "{{ workshop }}"
      workshop_prefix: "{{ workshop_prefix }}"
  register: ec2_igw

- debug:
    var: ec2_igw

- name: define ports list for security groups
  set_fact:
    ports_list_of_dicts: |
        {% set res = [] -%}
        {% if ports.tcp != None %}
        {% for key in ports.tcp.keys() -%}
           {% for value in ports.tcp[key] -%}
            {% set ignored = res.extend([{ 'proto': 'tcp', 'ports': key, 'rule_desc': value, 'cidr_ip': '0.0.0.0/0' }]) -%}
           {%- endfor %}
        {%- endfor %}
        {%- endif %}
        {% if ports.udp != None %}
        {% for key in ports.udp.keys() -%}
           {% for value in ports.udp[key] -%}
            {% set ignored = res.extend([{ 'proto': 'udp', 'ports': key, 'rule_desc': value, 'cidr_ip': '0.0.0.0/0' }]) -%}
           {%- endfor %}
        {%- endfor %}
        {%- endif %}
        {{ res }}

- debug:
    var: ports_list_of_dicts

- name: Create RHEL security group
  ec2_group:
    name: "{{ workshop_abbrev }}-{{ workshop_prefix }}-rhel-sg"
    description: "SG for RHEL hosts"
    region: "{{ region }}"
    vpc_id: "{{ ec2_vpc.vpc.id }}"
    rules: "{{ ports_list_of_dicts }}"
    tags:
      username: "{{ local_user }}"
      workshop: "{{ workshop }}"
      workshop_prefix: "{{ workshop_prefix }}"
      rhel: "{{ workshop_abbrev }}-{{ workshop_prefix }}"
    state: present
  register: result

- debug:
    var: result

- name: Create Windows security group
  ec2_group:
    name: "{{ workshop_abbrev }}-{{ workshop_prefix }}-win-sg"
    description: "SG for Windows hosts"
    region: "{{ region }}"
    vpc_id: "{{ ec2_vpc.vpc.id }}"
    rules: "{{ ports_list_of_dicts }}"
    tags:
      username: "{{ local_user }}"
      workshop: "{{ workshop }}"
      workshop_prefix: "{{ workshop_prefix }}"
      win: "{{ workshop_abbrev }}-{{ workshop_prefix }}"
    state: present
  register: result

- debug:
    var: result

- name: Create public subnet
  ec2_vpc_subnet:
    cidr: "10.0.2.0/24"
    region: "{{ region }}"
    vpc_id: "{{ ec2_vpc.vpc.id }}"
    tags:
      Name: "{{ workshop_abbrev }}-{{ workshop_prefix }}-subnet"
      username: "{{ local_user }}"
      workshop: "{{ workshop }}"
      workshop_prefix: "{{ workshop_prefix }}"
    wait: yes
  register: ec2_subnet

- debug:
    var: ec2_subnet

- name: Create private subnet
  ec2_vpc_subnet:
    cidr: "10.0.3.0/24"
    region: "{{ region }}"
    vpc_id: "{{ ec2_vpc.vpc.id }}"
    tags:
      Name: "{{ workshop_abbrev }}-{{ workshop_prefix }}-private-subnet"
      username: "{{ local_user }}"
      workshop: "{{ workshop }}"
      workshop_prefix: "{{ workshop_prefix }}"
    wait: yes
  register: ec2_private_subnet

- debug:
    var: ec2_subnet

- name: Create VPC route table
  ec2_vpc_route_table:
    region: "{{ region }}"
    vpc_id: "{{ ec2_vpc.vpc.id }}"
    subnets:
      - "{{ ec2_subnet.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ ec2_igw.gateway_id }}"
    lookup: tag
    tags:
      Name: "{{ workshop_abbrev }}-{{ workshop_prefix }}-route"
      username: "{{ local_user }}"
      workshop: "{{ workshop }}"
      workshop_prefix: "{{ workshop_prefix }}"
    state: present
  register: ec2_route

- debug:
    var: ec2_route

- name: Create RHEL admin host
  ec2:
    assign_public_ip: yes
    key_name: "{{ workshop_abbrev }}-{{ workshop_prefix }}-key"
    group: "{{ workshop_abbrev }}-{{ workshop_prefix }}-rhel-sg"
    region: "{{ region }}"
    instance_type: "{{ rhel_instance_type }}"
    image: "{{ rhel_ami.stdout if auto_ami == true else regions[region][rhel_ver].ami }}"
    vpc_subnet_id: "{{ ec2_subnet.subnet.id }}"
    wait: true
    instance_tags:
      Name: "{{ workshop_abbrev }}-{{ workshop_prefix }}-admin"
      username: "{{ local_user }}"
      workshop_prefix: "{{ workshop_prefix }}"
      rhel_admin: "{{ workshop_abbrev }}-{{ workshop_prefix }}"
      # RH IT Required Tags
      ServiceName: "{{ workshop_abbrev }}-{{ workshop_prefix }}-admin"
      ServiceOwner: "{{ local_user }}"
      ServicePhase: "{{ workshop_phase }}"
      BusinessUnit: "415"
      AppCode: "{{ workshop_appCode }}"
    exact_count: "{{ admin_rhel_count }}"
    count_tag: rhel_admin
  register: ec2_rhel_admin

- name: Create RHEL instances
  ec2:
    assign_public_ip: yes
    key_name: "{{ workshop_abbrev }}-{{ workshop_prefix }}-key"
    group: "{{ workshop_abbrev }}-{{ workshop_prefix }}-rhel-sg"
    region: "{{ region }}"
    instance_type: "{{ rhel_instance_type }}"
    image: "{{ rhel_ami.stdout if auto_ami == true else regions[region][rhel_ver].ami }}"
    vpc_subnet_id: "{{ ec2_subnet.subnet.id }}"
    volumes: "{{ rhel_instance_vols }}"
    wait: true
    instance_tags:
      Name: "{{ workshop_abbrev }}-{{ workshop_prefix }}-rhel"
      username: "{{ local_user }}"
      workshop_prefix: "{{ workshop_prefix }}"
      rhel: "{{ workshop_abbrev }}-{{ workshop_prefix }}"
      # RH IT Required Tags
      ServiceName: "{{ workshop_abbrev }}-{{ workshop_prefix }}-admin"
      ServiceOwner: "{{ local_user }}"
      ServicePhase: "{{ workshop_phase }}"
      BusinessUnit: "415"
      AppCode: "{{ workshop_appCode }}"
    exact_count: "{{ rhel_count }}"
    count_tag: rhel
  register: ec2_rhel

- name: Create RHEL Bastion instances (container security)
  amazon.aws.ec2:
    assign_public_ip: yes
    key_name: "{{ workshop_abbrev }}-{{ workshop_prefix }}-key"
    group: "{{ workshop_abbrev }}-{{ workshop_prefix }}-rhel-sg"
    region: "{{ region }}"
    instance_type: "{{ bastion_instance_type }}"
    image: "{{ rhel_ami.stdout if auto_ami == true else regions[region][rhel_ver].ami }}"
    vpc_subnet_id: "{{ ec2_subnet.subnet.id }}"
    wait: true
    instance_tags:
      Name: "{{ workshop_abbrev }}-{{ workshop_prefix }}-bastion_rhel"
      username: "{{ local_user }}"
      workshop_prefix: "{{ workshop_prefix }}"
      bastion_rhel: "{{ workshop_abbrev }}-{{ workshop_prefix }}"
      # RH IT Required Tags
      ServiceName: "{{ workshop_abbrev }}-{{ workshop_prefix }}-admin"
      ServiceOwner: "{{ local_user }}"
      ServicePhase: "{{ workshop_phase }}"
      BusinessUnit: "415"
      AppCode: "{{ workshop_appCode }}"
    exact_count: "{{ student_count }}"
    count_tag: bastion_rhel
  register: ec2_bastion_rhel
  when: workshop == "container_security"

- name: Attach additional network interface to RHEL nodes
  ec2_eni:
    instance_id: "{{ item.id }}"
    device_index: 1
    subnet_id: "{{ ec2_private_subnet.subnet.id }}"
    private_ip_address: "10.0.3.{{ 10 + item.ami_launch_index|int }}"
    region: "{{ region }}"
    attached: yes
    state: present
  with_items: "{{ ec2_rhel.tagged_instances }}"
  register: eni

- debug:
    var: eni

- name: Set additional interfaces to auto delete on instance termination
  ec2_eni:
    eni_id: "{{ item.interface.id }}"
    delete_on_termination: yes
    region: "{{ region }}"
  with_items: "{{ eni.results }}"
  register: eni_results

- debug:
    var: eni_results

- name: Create RHEL Tower instances
  ec2:
    assign_public_ip: yes
    key_name: "{{ workshop_abbrev }}-{{ workshop_prefix }}-key"
    group: "{{ workshop_abbrev }}-{{ workshop_prefix }}-rhel-sg"
    region: "{{ region }}"
    instance_type: "{{ tower_instance_type }}"
    image: "{{ rhel_ami.stdout if auto_ami == true else regions[region][rhel_ver].ami }}"
    vpc_subnet_id: "{{ ec2_subnet.subnet.id }}"
    wait: true
    instance_tags:
      Name: "{{ workshop_abbrev }}-{{ workshop_prefix }}-tower_rhel"
      username: "{{ local_user }}"
      workshop_prefix: "{{ workshop_prefix }}"
      tower_rhel: "{{ workshop_abbrev }}-{{ workshop_prefix }}"
    exact_count: "{{ tower_rhel_count }}"
    count_tag: tower_rhel
  register: ec2_tower_rhel
  when: tower_rhel_count is defined

- name: Create Windows instances
  ec2:
    assign_public_ip: yes
    key_name: "{{ workshop_abbrev }}-{{ workshop_prefix }}-key"
    group: "{{ workshop_abbrev }}-{{ workshop_prefix }}-win-sg"
    region: "{{ region }}"
    instance_type: "{{ win_instance_type }}"
    image: "{{ windows_ami.stdout if auto_ami == true else regions[region][win_ver].ami }}"
    vpc_subnet_id: "{{ ec2_subnet.subnet.id }}"
    user_data: "{{ lookup('file', '{{ winrm_path }}') }}"
    wait: true
    instance_tags:
      Name: "{{ workshop_abbrev }}-{{ workshop_prefix }}-win"
      username: "{{ local_user }}"
      workshop_prefix: "{{ workshop_prefix }}"
      win: "{{ workshop_abbrev }}-{{ workshop_prefix }}"
    exact_count: "{{ win_count }}"
    count_tag: win
  register: ec2_win

- debug:
    var: ec2_rhel_admin

- debug:
    var: ec2_rhel

- debug:
    var: ec2_tower_rhel

- debug:
    var: ec2_win

#- name: write created host data to files
#  block:

#    - name: write admin host data to file
#      template:
#        src: "facts.j2"
#        dest: "{{ deploy_working_dir }}/ec2_rhel_admin.fact"
#      delegate_to: localhost
#      loop: "{{ ec2_rhel_admin.items() | list }}"

#    - name: write rhel host data to file
#      template:
#        src: "facts.j2"
#        dest: "{{ deploy_working_dir }}/ec2_rhel.fact"
#      delegate_to: localhost
#      loop: "{{ ec2_rhel.items() | list }}"

#    - name: write tower host data to file
#      template:
#        src: "facts.j2"
#        dest: "{{ deploy_working_dir }}/ec2_tower_rhel.fact"
#      delegate_to: localhost
#      loop: "{{ ec2_tower_rhel.items() | list }}"

#    - name: write windows host data to file
#      template:
#        src: "facts.j2"
#        dest: "{{ deploy_working_dir }}/ec2_win.fact"
#      delegate_to: localhost
#      loop: "{{ ec2_win.items() | list }}"

#===============================================================================
#  Verify hosts online
#===============================================================================

#---------------------------------------------------
#  RHEL
#---------------------------------------------------

- name: wait for SSH to answer on all hosts
  wait_for:
    port: 22
    host: "{{ item.public_ip }}"
    timeout: 300
  with_items: "{{ ec2_rhel.tagged_instances }}"

- name: add RHEL hosts to groups
  add_host:
    name: "{{ workshop_abbrev }}-{{ workshop_prefix }}-rhel-{{ item.id }}"
    ansible_ssh_host: "{{ item.public_ip }}"
    groups: rhel_nodes
  with_items: "{{ ec2_rhel.tagged_instances }}"

- name: add IP addresses to inventory
  lineinfile:
    path: "{{ inventory_working_dir }}/hosts"
    regex: "^node-{{ item.ami_launch_index }}.{{ workshop_prefix }}.{{ domain_name }}"
    line: "node-{{ item.ami_launch_index }}.{{ workshop_prefix }}.{{ domain_name }} ansible_ssh_host={{ item.public_ip }}"
  with_items: "{{ ec2_rhel.instances }}"

- debug:
    msg: "Create DNS record admin.{{ workshop_prefix }}.{{ domain_name }} pointing to {{ item.dns_name }}"
  loop: "{{ ec2_rhel_admin.instances }}"

- name: Create DNS records for RHEL admin
  route53:
    zone: "{{ domain_name }}"
    type: "CNAME"
    ttl: "300"
    record: "admin.{{ workshop_prefix }}.{{ domain_name }}"
    value: "{{ item.dns_name }}"
#    wait: yes
    overwrite: "{{ force_dns }}"
    state: present
  loop: "{{ ec2_rhel_admin.instances }}"

- name: Create DNS records for RHEL
  route53:
    zone: "{{ domain_name }}"
    type: "CNAME"
    ttl: "300"
    record: "node-{{ item.ami_launch_index }}.{{ workshop_prefix }}.{{ domain_name }}"
    value: "{{ item.dns_name }}"
#    wait: yes
    overwrite: "{{ force_dns }}"
    state: present
  loop: "{{ ec2_rhel.instances }}"
#  ignore_errors: true
  when: workshop != "container_security"

- name: Create DNS records for RHEL (container security)
  route53:
    zone: "{{ domain_name }}"
    type: "CNAME"
    ttl: "300"
    record: "{{ dns_name_list['stdout_lines'][ansible_loop.index0] }}"
    value: "{{ item.dns_name }}"
    overwrite: yes
#    wait: yes
    state: present
  loop: "{{ ec2_rhel.instances }}"
  loop_control:
    extended: yes
#  ignore_errors: true
  when: workshop == "container_security"

- name: Create DNS records for RHEL bastions (container security)
  route53:
    zone: "{{ domain_name }}"
    type: "CNAME"
    ttl: "300"
#    record: "{{ workshop_prefix }}.bastion.{{ item.ami_launch_index }}.{{ domain_name }}"
    record: "bastion-{{ item.ami_launch_index }}.{{ workshop_prefix }}.{{ domain_name }}"
    value: "{{ item.dns_name }}"
    overwrite: yes
#    wait: yes
    state: present
  loop: "{{ ec2_bastion_rhel.instances }}"
  when: workshop == "container_security"

- name: Create DNS records for RHEL Towers
  route53:
    zone: "{{ domain_name }}"
    type: "CNAME"
    ttl: "300"
    record: "tower-{{ item.ami_launch_index }}.{{ workshop_prefix }}.{{ domain_name }}"
    value: "{{ item.dns_name }}"
#    wait: yes
    overwrite: "{{ force_dns }}"
    state: present
  loop: "{{ ec2_tower_rhel.instances }}"
  when: tower_rhel_count is defined

#---------------------------------------------------
#  Windows
#---------------------------------------------------

- name: wait for WinRM to answer on all hosts
  wait_for:
    port: 5986
    host: "{{ item.public_ip }}"
    timeout: 300
  with_items: "{{ ec2_win.tagged_instances }}"

- name: add Windows hosts to groups
  add_host:
    name: "{{ workshop_abbrev }}-{{ workshop_prefix}}-win-{{ item.id }}"
    ansible_ssh_host: "{{ item.public_ip }}"
    groups: win_nodes
  with_items: "{{ ec2_win.tagged_instances }}"

- name: Create DNS records for Windows
  route53:
    zone: "{{ domain_name }}"
    type: "CNAME"
    ttl: "300"
    record: "win2016-{{ item.ami_launch_index }}.{{ workshop_prefix }}.{{ domain_name }}"
    value: "{{ item.dns_name }}"
#    wait: yes
    overwrite: "{{ force_dns }}"
    state: present
  loop: "{{ ec2_win.instances }}"
#  ignore_errors: true

#---------------------------------------------------
#  Ansible Hosts Creation
#---------------------------------------------------
- name: Template Ansible Hosts File
  template:
    dest: "{{ inventory_working_dir }}/hosts"
    src: "hosts.j2"
  when: execution is defined

...
