# file: 2_load.yml
---
# https://www.terraform.io/docs/providers/aws/index.html

- name: Wait for AWS AMIs to become initialized
  hosts: localhost
  tasks:
    - wait_for:
        host: "{{ item }}"
        port: 22
        state: started
        timeout: 300
      with_items: "{{ groups.all_nodes }}"
      when: cloud == "aws"

- name: Configure repositories on all nodes
  become: yes
  remote_user: "{{ system_user }}"
  hosts: all_nodes
  roles:
    - subscription_manager
    - repo_epel
    - nodejs 
    - wetty
    - zsh
    - cockpit
    - LetsEncrypt
    - ansible.tower

# Conditionally added below via group_vars/all
# jboss:       True
# walkthrough: True
# upgrade:     True


# JBOSS
- name: Stage Maven POMs
  become: yes
  remote_user: "{{ system_user }}"
  hosts: nodes
  roles:
    - { role: poms, when: jboss }

# WALKTHROUGH
- name: Prep walkthroughs for deployment
  become: yes
  remote_user: "{{ system_user }}"
  hosts: tower_nodes
  vars:
    install: no
    prep: yes
  roles:
    - { role: ansible.tower, when: walkthrough }
    - { role: codiad, when: walkthrough }

# Upgrade
- name: Upgrade packages
  become: yes
  remote_user: "{{ system_user }}"
  hosts: all_nodes
  roles:
    - { role: upgrade, when: upgrade }

