# file: 3_unregister.yml
---

Do not use with Cloud Access
- name: Unregister Nodes 
  become: yes
  hosts: all_nodes
  remote_user: "{{ system_user }}"
  roles:
    - unregister

- name: Remove infrastructure using Terraform
  hosts: local_target
  roles:
    - role: orock.infra
      tags: ['tagged','delete']
    
  # - name: Delete AWS Environment
  #   terraform:
  #     project_path: "{{ terraform_working_dir }}"
  #     state: absent
  #   when: cloud == "aws"